### ISSUE TITLE
Phone Number Format Validation

### ISSUE THREAD

**Issue by kevinmichaelchen** [Niupiao/niupiao-market#99]
https://github.com/joost/phony_rails

**Comment by rynkwn** [comment]
Took a very long time to get around to this, but thanks Kevin! Adding the gem + the relevant validation now

**Comment by rynkwn** [comment]
Though, sadly, the gem doesn't validate for Mongolian numbers. And the complexity is sufficient that it would be best for someone who's familiar with their phone numbering system to do it manually.
